"""Add is_dispatched column to Truck

Revision ID: 037a64c466c7
Revises: 943203b996e0
Create Date: 2024-11-22 10:51:33.950193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037a64c466c7'
down_revision = '943203b996e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_location', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dispatched', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('is_dispatched')

    op.drop_table('report')
    # ### end Alembic commands ###
