"""Add image_url to LitterHotspot

Revision ID: 04b6f08bde6d
Revises: 0534d5a1a719
Create Date: 2024-09-23 10:12:03.274971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b6f08bde6d'
down_revision = '0534d5a1a719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter_hotspot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter_hotspot', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
