"""Fix model relationships

Revision ID: 0534d5a1a719
Revises: 62880177c8ca
Create Date: 2024-09-20 15:38:01.247273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0534d5a1a719'
down_revision = '62880177c8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_hotspot_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['litter_hotspot_id'], ['litter_hotspot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatches')
    # ### end Alembic commands ###
