"""Add latitude and longitude to Dispatch

Revision ID: 62880177c8ca
Revises: adad0804fe78
Create Date: 2024-09-20 15:32:50.298247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62880177c8ca'
down_revision = 'adad0804fe78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatches')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('litter_hotspot_id', sa.INTEGER(), nullable=False),
    sa.Column('truck_id', sa.INTEGER(), nullable=False),
    sa.Column('dispatched_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['litter_hotspot_id'], ['litter_hotspot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
