"""Add litter_hotspot_id to Truck

Revision ID: 943203b996e0
Revises: a195f30627b8
Create Date: 2024-10-02 09:49:36.612378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943203b996e0'
down_revision = 'a195f30627b8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('litter_hotspot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_truck_litter_hotspot', 'litter_hotspot', ['litter_hotspot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('litter_hotspot_id')

    # ### end Alembic commands ###
