"""Added foreign key between Truck and LitterHotspot

Revision ID: a195f30627b8
Revises: 22f33892ac5d
Create Date: 2024-09-25 10:41:59.472671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a195f30627b8'
down_revision = '22f33892ac5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truck')
    # ### end Alembic commands ###
