"""add dispatches table

Revision ID: adad0804fe78
Revises: 8505301177a3
Create Date: 2024-09-19 16:59:33.577914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adad0804fe78'
down_revision = '8505301177a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_hotspot_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['litter_hotspot_id'], ['litter_hotspot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatches')
    # ### end Alembic commands ###
